### PR TITLE
add .usdc and .usdz export

### PR DESCRIPTION
**Pull request by ox**
So after taking a look at usdcat and usdzip, I tried to use `pxr.Ar` to resolve assets and `UsdUtils.CreateNewUsdzPackage`. I would like this code reviewed + checked. I think it's correct but if anyone can run models against it to make sure the resulting USDZ files are correct that'd be appreciated.

helps #9

### CODE REVIEW

**Comment by ox** [comment]
Also not sure if compliance failure should actually stop usdz creation. My thinking is that a non-compliant USD file is wrong and the program should fail 

Todo: add an exit code of 1 for failures

**Comment by ox** [comment]
@wave-electron does this patch create valid USDZ files for you? I'm still having difficulties with iOS 12 Beta 12 :(

**Comment by wave-electron** [comment]
@ox I tried the patch. It created the usdz file, which previewed in ios12 beta12 for the hand animation attached. However, the bone animation won't run unless I  manually edit the joint structure to ensure [closed issue 22](https://github.com/kcoley/gltf2usd/issues/22) is met. I've attached example of the two hand.usda files & the resulting hand_edited.usdz which animates in IO12 after manually editing! 
[hand_edited.zip](https://github.com/kcoley/gltf2usd/files/2358989/hand_edited.zip)

This  bug needs to be addressed, before much progress can be made.

**Comment by kcoley** [comment]
@ox the @wave-electron I will create an issue to implement the workaround officially in the project.  I was hoping it would be resolved in a beta update, but I will implement the change

**Pull request merged**
