### PR TITLE
Add BlendShape support

### LINKED ISSUE #16: unsupported animation target path weights
@kcoley 

```
raise Exception('Unsupported animation target path! {}'.format(target_path))
Exception: Unsupported animation target path! weights
```
You can download this model from here. [buster_drone glTF autoconverted format](https://sketchfab.com/models/294e79652f494130ad2ab00a13fdbafd)

To get this animation to build I removed the paths referring to weights in the glTF ascii file. However, the usda animation is distorted.

### LINKED ISSUE #18: morph targets are not implemented
Implement morph targets, which should help with https://github.com/kcoley/gltf2usd/issues/17

### PR DESCRIPTION
**Pull request by ox**
This diff adds support for BlendShapes and animated weights for them. First we define a`SkelRoot` for each `Mesh`, then giving it a `Skeleton/SkelAnimation` with all of the defined BlendShape tokens. Then for each BlendShape we set the offsets that Mesh applies when that weight is at full strength. Finally, it goes over each input keyframe and correctly fetches chunks of N entities from the output accessor for N defined blend shapes.

closes #16 
closes #18

### CODE REVIEW

**Comment by ox** [comment]
I'm having issues getting anything with `BlendShape` to render in iOS 12, Beta 12. I can't even get a preview. I'll review the Schema and double check that everything is right.

**Comment by wave-electron** [comment]
This is not just an issue with BlendShape, all recent bone animations I've tried, in some cases may animate in xcode10 beta 6, but don't even preview in IOS 12, Beta 12 right now. There may be some other reason for this problem. Its puzzling me.

**Comment by wave-electron** [comment]
Sorry the bone animations are previewing, but only as the T-pose or resting pose.

**Comment by ox** [comment]
Interesting. Is there a definitive tool that can render USD at-spec?

**Comment by wave-electron** [comment]
@ox my issue with bone animations only working in xcode but  not running in IOS only previewing as rest pose was resolved as 
[22](https://github.com/kcoley/gltf2usd/issues/22). This is a real gotcha... You need to make sure the first joint name is by itself.

**Comment by ox** [comment]
I think this PR might be incorrect b/c it creates a Skeleton for the model, as does `_convert_skin_to_usd`. The SkelRoot should be created and in both cases and the skeletons should be able to contain both joint motion + BlendShapes

**Comment by kcoley** [comment]
@ox I thought that Apple may have a reference implementation in their USDPython code, but I don't see any sample models with blend shapes, unless I overlooked it.  

As for SkelRoot, I worked on a change last night that will apply it when a mesh primitive has joints and weights.  I am still troubleshooting the animation data, but so far it seems that XCode tends to not behave differently whether it is applied or not

**Comment by ox** [comment]
are you referring to your `refactorSkeletons` branch? Should I work off that branch instead?

**Comment by ox** [comment]
@kcoley any chance you can take a look at this? What next steps should I take to get blendshapes in?

**Comment by kcoley** [comment]
@ox sure thing, I can take a look at it later today.  If I can find a reference blend shape usda I'll compare against it.  Otherwise I'll merge to the project

**Comment by kcoley** [comment]
@ox LGTM.  I can't find any blend shape usd models.  I also didn't have much luck when attempting to create on with Maya.

**Pull request merged**
